name: Run Tests and Tag

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        PYTHONPATH=${PWD} pytest

  tag:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Create tag
      id: tag
      run: |
        VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
        if [ -z "$VERSION" ]; then
          VERSION=0.0.0
        fi
        VERSION_BITS=(${VERSION//./ })
        MAJOR=${VERSION_BITS[0]}
        MINOR=${VERSION_BITS[1]}
        PATCH=${VERSION_BITS[2]}
        PATCH=$((PATCH + 1))
        NEW_TAG="$MAJOR.$MINOR.$PATCH"
        git tag $NEW_TAG
        echo "::set-output name=tag::$NEW_TAG"

    - name: Push tag
      run: |
        git push origin ${{ steps.tag.outputs.tag }}
